[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.134.2"
  HUGO_ENV = "production"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://jiandan.netlify.app"  #返回首页地址在此修改

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"