[zh-cn]
title = "小威的EMO"
weight = 1
LanguageName = "zh-cn"
contentDir = "content/cn"

#[en]
#title = "My blog"
#weight = 2
#LanguageName = "EN"
#contentDir = "content/english"

#[ar]
#title = "فلانة الفلانية"
#contentDir = "content/arabic" 
#weight = 3
#LanguageDirection = "rtl" 
#LanguageName = "AR"
#[ar.params]
#description = "أنا أعمل كمطورة ويب في شركة س"