  [[main]]
  name = "首页"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "存档"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "作品"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "关于"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "留言"
  weight = 500
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "简单导航"
  weight = 1
  identifier = "jiandan"
  url = "https://432600.xyz/"

  [[footer]]
  name = "小威的博客"
  weight = 2
  identifier = "xw"
  url = "https://blog.432600.xyz/"